version: '3.9'
networks:
  app-ts:
    driver: bridge
services:
  tagspaces-web:
    build: .
    ports:
      - '8080:80'
    networks:
      - app-ts
  minio:
    image: 'minio/minio'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
    command: server --console-address ":9001"  /data
    networks:
      - app-ts
