/**
 * TagSpaces - universal file and folder organizer
 * Copyright (C) 2024-present TagSpaces GmbH
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License (version 3) as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

import AppConfig from '-/AppConfig';
import TsButton, { TSButtonProps } from '-/components/TsButton';
import { TabNames } from '-/hooks/EntryPropsTabsContextProvider';
import { useChatContext } from '-/hooks/useChatContext';
import { useFilePropertiesContext } from '-/hooks/useFilePropertiesContext';
import { useNotificationContext } from '-/hooks/useNotificationContext';
import { useOpenedEntryContext } from '-/hooks/useOpenedEntryContext';
import { formatDateTime } from '@tagspaces/tagspaces-common/misc';
import { extractFileExtension } from '@tagspaces/tagspaces-common/paths';
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { AIIcon } from '../CommonIcons';
import {
  actions as SettingsActions,
  getDefaultAIProvider,
} from '-/reducers/settings';
import { AppDispatch } from '-/reducers/app';
import { useDispatch, useSelector } from 'react-redux';
import { AIProvider } from '-/components/chat/ChatTypes';
import { TS } from '-/tagspaces.namespace';
import { useIOActionsContext } from '-/hooks/useIOActionsContext';

type Props = TSButtonProps & {};

function AiGenDescButton(props: Props) {
  const { t } = useTranslation();
  const { style, disabled } = props;
  const dispatch: AppDispatch = useDispatch();
  const defaultAiProvider: AIProvider = useSelector(getDefaultAIProvider);
  const { openedEntry } = useOpenedEntryContext();
  const { setDescriptionChange } = useIOActionsContext();
  const { getEntryModel, descriptionGenerate } = useChatContext();
  const { setDescription, saveDescription } = useFilePropertiesContext();
  const { showNotification } = useNotificationContext();

  const [isLoading, setIsLoading] = useState<boolean>(false);

  const openedEntryModel = getEntryModel(openedEntry?.name, defaultAiProvider);
  if (!openedEntry || !openedEntryModel) {
    return null;
  }

  function handleGenerationResults(entries: TS.FileSystemEntry[]) {
    //console.log('newOllamaMessage response:' + response);
    setIsLoading(false);
    const promises = entries.map((entry) => {
      if (entry && entry.uuid === openedEntry.uuid) {
        dispatch(SettingsActions.setEntryContainerTab(TabNames.descriptionTab));
        setDescription(entry.meta.description);
        return saveDescription();
      } else {
        return setDescriptionChange(entry, entry.meta.description);
      }
    });
    Promise.all(promises).then(() => {
      showNotification(
        'Description for ' + openedEntry.name + ' generated by an AI.',
      );
    });
  }

  return (
    <TsButton
      loading={isLoading}
      disabled={isLoading || disabled}
      tooltip="Uses currently configured AI model to generate description for this file"
      startIcon={<AIIcon />}
      data-tid="generateDescriptionAITID"
      style={style}
      onClick={() => {
        setIsLoading(true);
        descriptionGenerate([openedEntry]).then((entries) => {
          handleGenerationResults(entries);
        });
      }}
    >
      {t('core:generateDescription')}
    </TsButton>
  );
}

export default AiGenDescButton;
